apiVersion: v1
kind: ConfigMap
metadata:
  name: alpine-demo-config
data:
  message: "Hello from Alpine + Argo CD!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-demo
  labels:
    app: alpine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-demo
  template:
    metadata:
      labels:
        app: alpine-demo
    spec:
      containers:
        - name: alpine
          image: alpine:3.19
          command: ["/bin/sh", "-c"]
          args:
            - echo "$(cat /etc/config/message)"; sleep 3600
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
          readinessProbe:
            exec:
              command: ["cat", "/etc/config/message"]
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: alpine-demo-config