apiVersion: v1
kind: ConfigMap
metadata:
  name: alpine-demo-config
data:
  STARTUP_MESSAGE: "🚀 Hello from a secure Alpine container via Argo CD!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-alpine-demo
  labels:
    app: secure-alpine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-alpine-demo
  template:
    metadata:
      labels:
        app: secure-alpine-demo
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001  # This should match your Dockerfile UID
      containers:
        - name: alpine
          image: ciaa/demo_app:v1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: STARTUP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: alpine-demo-config
                  key: STARTUP_MESSAGE
            - name: SLEEP_DURATION
              value: "7200"
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            exec:
              command: ["sh", "-c", "test -f ./entrypoint.sh"]
            initialDelaySeconds: 3
            periodSeconds: 10