---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    PASS1: AgDJRyikLRUIwnZDxC660fcDgdr1CGzglLCLHr7wGoldDjUsFKKMV7gVPYri1G6pH6phAi9bl8gbKlnwkOdPBGSvMr5+Kzrhh/S3U1tuVAKTiS25fOVSZFQ6UjepP2CdmNV13q+OYbCOVXftEmgHg+/RkjPPcVlj2B3njYNJjNUZNdc1efPu06WEtlpR1e9wZn7YoE1gTlh3r4Kx/lb/4nz4kYFZsPGyzCz+hw9r5MjlmUNga3uNWP+2XEiKaJS1Ayh6knU2xXrXyRiUojV/7+ST6t6dwLXJ6l7Z5pRoD1tIXrOI17JeQGKmOGnW1J0OOlCaZ0s0+2mbck6Tth6Bowmpzn34D4ptDywdjTkdsGbxkn89lwp0+/TwiCtrAF8q9sudSkN/ryIN4qdnaQxf955Ww/QKnYoyY7dqv4O8Id0ZTypPxud5oLN00/laKCiX1kHVLoi4cqLvKyTUES9rTLxgBP/4Hv4DBjpfXhs/DUjhj9xSgFMB9JRCGxpM9KHY8UT636pful5dQV8yeS9nZ39IGyuVpZfYa12SxvPbSTVHRt71g8FZpvu5NHsiFDrjD/Zhp/gMwlmUEPh6uAqxnhP7R9C1VRSYpuk6cdepZLgRX/8M6RDT+8lV7w3amVaCksBfi5Xv1p1sGkHO3rsMwJtZKsSpiKOWtT/nIS4fE3xvuy42lr+EJQ9z+M14dnGBIQZD8t/e
    PASS2: AgAYrP56zfdLu3jBQDivOZu9ClibKMz6lCN9BtHOKy3B2YPaqs5ygP5ysuWah1pQlIlAngoS+H7tWmhpkJG9UKutVYfjA3Q6DQ4YLvW916eALuVCUu+kyAyY2VyBfnRydKA331KY29eiTQHWXYlJZcTemnbTD8HdhGF7wwQ7y+APEqN8P8fVX9hF26yuPnOCfhi5hFqgRgfrJV3kZoMC/+Wfz0c8P+BPenGYQknWLb6palzVud2IzoqDEMotD/C+8ishOfPezqmo9GTFGyhgEnr1VRuR4Eit/uH6ePb97+XlbvPABHkCe8v2vk9Q5XU9K+FotEQ4pImMRlCKjzRJiXMMGvfzJstP6gkrjzssgfIENwBQv3LzUze5jQfhfoFE1G65tVmtbvQ9nG3FGb/jNi6NAufLi4Pc/fD5eVEluwbraDkpMvziTIm4hoEZPTwLFijduAEEwGfwZhtk/rUS8hXZCYXboNwKB5rgBbUkQPvAtlGJkeJyA8KuWDf9soeUTnK/a286/70o0WkshQJE1l9FaTXhsTa1l+RhmriTkgpG0p4iGwLHtRFLvh12avK+vdFfZc6aFyCj7kxQ1GKBymruYZ1mDLcG6Hv8E0yUu/QWgzZM9WjH4i9dQunDmHwQXF23qnNn1+///zGuZbXco7AIeRPWDrMccrneVljIe7Az47XXoaQ24m9KVHVj9YWBt9d3CXza
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
