# Basic example of a workflow
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-s3-
  namespace: playground
spec:
  serviceAccountName: playground-sa
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: hello-world-to-file
    - - name: consume-artifact
        template: print-message-from-file
        arguments:
          parameters:
          - name: message-to-add
            value: "This is a new line in the file"
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: hello-world-to-file
    container:
      image: busybox
      command: [sh, -c]
      args: ["sleep 1; echo I am using argo workflows | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt
        s3:
          endpoint: s3-de-central.profitbricks.com:443
          bucket: customerintelligence
          region: eu-central-1
          key: argo/hello_world.txt.tgz
          accessKeySecret:
            name: s3-credentials
            key: accessKey
          secretKeySecret:
            name: s3-credentials
            key: secretKey

  - name: print-message-from-file
    inputs:
      parameters:
       - name: message-to-add
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ['echo {{inputs.parameters.message-to-add}} >> /tmp/message && cat /tmp/message']
